apiVersion: v1
kind: Pod
spec:
  containers:
    - name: shell
      image: ubuntu
      command:
        - sleep
      args:
        - infinity
    - name: maven
      image: maven:3.6.3-openjdk-11-slim
      command: ["tail", "-f", "/dev/null"]  # this or any command that is bascially a noop is required, this is so that you don't overwrite the entrypoint of the base container
      imagePullPolicy: Always # use cache or pull image for agent
#      resources:  # limits the resources your build contaienr
#        requests:
#          memory: "800Mi"
#          cpu: "500m"
#        limits:
#          memory: "1Gi"
    - name: docker
      image: docker:19.03.1
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run
    - name: docker-daemon
      image: docker:19.03.1-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run
  volumes:
    - name: docker-socket
      emptyDir: {}
#      volumeMounts:
#        - name: workspace-volume
#          mountPath: /home/jenkins/agent
#        workingDir: "/home/jenkins/agent"
#  volumes:
#    - name: "workspace-volume"
#      persistentVolumeClaim:
#        claimName: "jenkins-worker-pvc"
#        readOnly: false